// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAajUJSyvCBbd5tpdfrYLqqIduLRWhf2WY',
    appId: '1:313947281938:web:37e47a50f4c6f9a1b396cb',
    messagingSenderId: '313947281938',
    projectId: 'luwas-49aec',
    authDomain: 'luwas-49aec.firebaseapp.com',
    storageBucket: 'luwas-49aec.firebasestorage.app',
    measurementId: 'G-PJHPV0B5WX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASZ0P3H3JOdOjSrh10LBG5D-GGxdcZjbw',
    appId: '1:313947281938:ios:79144b818cc57246b396cb',
    messagingSenderId: '313947281938',
    projectId: 'luwas-49aec',
    storageBucket: 'luwas-49aec.firebasestorage.app',
    iosClientId: '313947281938-462li3soike9lbd5nmle1n9ese9n2r37.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailPasswordLogin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASZ0P3H3JOdOjSrh10LBG5D-GGxdcZjbw',
    appId: '1:313947281938:ios:a1d5e90e3e7905e4b396cb',
    messagingSenderId: '313947281938',
    projectId: 'luwas-49aec',
    storageBucket: 'luwas-49aec.firebasestorage.app',
    iosClientId: '313947281938-u72if6ur2dfrqo66ai0ao405fku61m3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailpasswordlogin',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe74ZkwMmK4uIzxTs1PoXobw312YISWWw',
    appId: '1:313947281938:android:762190413337d681b396cb',
    messagingSenderId: '313947281938',
    projectId: 'luwas-49aec',
    storageBucket: 'luwas-49aec.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAajUJSyvCBbd5tpdfrYLqqIduLRWhf2WY',
    appId: '1:313947281938:web:0a6ff9cfa96f616eb396cb',
    messagingSenderId: '313947281938',
    projectId: 'luwas-49aec',
    authDomain: 'luwas-49aec.firebaseapp.com',
    storageBucket: 'luwas-49aec.firebasestorage.app',
    measurementId: 'G-74PEWBQC5K',
  );

}